In [5]:
import numpy as np

In [8]:
np.arange(0,11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [10]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [16]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
np.random.rand(5)

array([0.06271165, 0.31852492, 0.64666039, 0.45625016, 0.94544621])

In [20]:
np.random.rand(5,5)

array([[0.23695711, 0.53425051, 0.09546034, 0.20443921, 0.14464863],
       [0.71948223, 0.37616744, 0.61048944, 0.95598516, 0.29436428],
       [0.95751842, 0.7066403 , 0.92146915, 0.81285711, 0.55411721],
       [0.23433486, 0.19510935, 0.98018607, 0.79923486, 0.37284893],
       [0.91784355, 0.26818733, 0.43036399, 0.95937033, 0.08773392]])

In [22]:
np.random.randn(4)

array([-1.35921461,  0.28532149,  0.7551313 ,  0.32189392])

In [23]:
np.random.randn(4,4)

array([[-1.63823632,  0.95363163, -0.51511147,  1.85616208],
       [ 0.58705183,  0.1424522 ,  1.33991839,  0.08202392],
       [-1.5434417 ,  1.81487672,  0.11863482,  0.3408625 ],
       [-0.54173944, -0.09704759,  0.21815986, -0.37012333]])

In [28]:
np.random.randint(0,100,10)

array([77, 93, 58,  4, 99,  0, 92, 50, 27, 55])

In [30]:
arr = np.arange(0,25)

In [33]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [34]:
rand_arr = np.random.randint(0,50,10)

In [35]:
rand_arr

array([ 8, 48, 28, 23, 30, 39,  6, 35,  0, 42])

In [38]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [39]:
rand_arr.max()

48

In [40]:
rand_arr.min()

0

In [41]:
rand_arr.argmax()

1

In [42]:
rand_arr.argmin()

8

In [43]:
arr.shape

(25,)

In [44]:
arr = arr.reshape(5,5)

In [45]:
arr.shape

(5, 5)

In [46]:
arr.dtype

dtype('int64')